# Site settings
title: Pyblish
email: marcus@abstractfactory.io
description: A plug-in driven automation framework for content.
version: "1.0.3"
baseurl: ""
url: "http://pyblish.com"

collections:
    - chapters
    - "1_0"
    - napoleon

# Enable Disqus
comments: true

# Build settings
markdown: redcarpet
redcarpet:
    # Extensions from here https://github.com/vmg/redcarpet/blob/v2.2.2/README.markdown#and-its-like-really-simple-to-use
    extensions: 
        - autolink
        - with_toc_data